Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,38 +1,41 @@
-name: Playit RDP Tunnel
-
+name: Playit RDP Tunnel Linux
 on:
   workflow_dispatch:
-
 jobs:
   setup-rdp-tunnel:
-    runs-on: windows-2025
-
+    runs-on: ubuntu-22.04
     steps:
     - name: Check out the repository
-      uses: actions/checkout@v2
-
+      uses: actions/checkout@v4
+    - name: Install Dependencies
+      run: |
+        sudo apt-get update
+        sudo apt-get install -y xrdp xfce4 xfce4-goodies
+        sudo systemctl enable xrdp
+        sudo systemctl start xrdp
+        echo "xfce4-session" > ~/.xsession
+    - name: Create and Configure User
+      run: |
+        sudo useradd -m -s /bin/bash runneradmin
+        echo "runneradmin:p@ssw0rd!" | sudo chpasswd  # Password di-hardcode
+    - name: Configure Firewall
+      run: |
+        sudo ufw allow 3389
+        sudo ufw reload
     - name: Download and Install Playit
       run: |
-        Invoke-WebRequest -Uri "https://github.com/playit-cloud/playit-agent/releases/download/v0.15.26/playit-windows-x86_64-signed.exe" -OutFile "$env:USERPROFILE\playit.exe"
-        Start-Sleep -Seconds 5  # Give some time for the download to complete
-
-        
-    # Default, optional.
-    - name: Enable TS
-      run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
-    - run: Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
-    - run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
-    - run: Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "p@ssw0rd!" -Force)
-
+        wget https://github.com/playit-cloud/playit-agent/releases/download/v0.15.26/playit-linux-x86_64 -O ~/playit
+        chmod +x ~/playit
     - name: Start Playit and Set Up RDP Tunnel
       env:
-        PLAYIT_AUTH_KEY: ${{ secrets.PL }} 
+        PLAYIT_AUTH_KEY: ${{ secrets.PL }}
       run: |
-        Start-Process -FilePath "$env:USERPROFILE\playit.exe" -ArgumentList "--secret $env:PLAYIT_AUTH_KEY" -NoNewWindow -Wait
-        Start-Process -FilePath "$env:USERPROFILE\playit.exe" -NoNewWindow
-
-        
-    # Prevent workflow to stop
+        ~/playit --secret $PLAYIT_AUTH_KEY &
+        sleep 5
+        if ! pgrep -x "playit" > /dev/null; then
+          echo "Playit failed to start"
+          exit 1
+        fi
     - name: Keep the GitHub Action Runner Alive
       run: |
-          Start-Sleep -Seconds 11800  # Adjust the duration based on your needs
+        sleep 11800
